# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dad1bb83b906bf553ed1827229ffe66ca9525c542037292532afb139cfd3f47572d0fb4c8dbee48ac4d678d54e26e2b05df7f9559c6abe4737fadec21a6f396

test:
  secret_key_base: 27e8bd88387d8c0480ca39feed88056150bb222b162f2129eb34de2c1c8f2acda5cdee3fc49103a5114d9de0b4afa1359ca73a5b431d9a1aaa1606ffe420aa06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
